language: node_js
node_js:
  - "6.7"
  - "6.0"
  - "5.0"
  - "4.0"
sudo: false
addons:
  code_climate:
    repo_token: a66b1c6b74ed5e95fa6817c162fb431e68742cfb7b8b842eaa07fdf43627bb7f
script: "npm run coverage"
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
